-- *
-- * Copyright (c) 2008-2024 Benoit Bouthillier. All rights reserved.
-- * Licensed under the MIT license.
-- * See LICENSE file in the project root for full license information.
-- *



---------------------------------------------
---------------------------------------------
---------------------------------------------
--  V E R S I O N   0 . 2 4  -   B e t a   --
---------------------------------------------
---------------------------------------------


ln -s /opt/tngfw/lib /usr/local/CAlib


ALTER TABLE TACHE_DET_MSG_AGT DROP CONSTRAINT TDMA_FK_TACHE_AGT;
ALTER TABLE HIST_TACHE_AGT    DROP CONSTRAINT HTA_FK_TACHE_AGT;

ALTER TABLE TACHE_AGT DROP CONSTRAINT TAC_CHK_EXECUTION;
ALTER TABLE TACHE_AGT DROP CONSTRAINT TAC_CHK_TYPE_NOTIF;

ALTER TABLE TACHE_AGT DROP CONSTRAINT TAC_PK_TACHE_AGT;
DROP INDEX TAC_PK_TACHE_AGT;

ALTER TABLE TACHE_AGT DROP CONSTRAINT TAC_FK_DESTI_NOTIF;


ALTER TABLE TACHE_AGT RENAME TO TACHE_AGT_OLD;

CREATE TABLE TACHE_AGT
(
   NOM_SERVEUR          VARCHAR2(64)                        NOT NULL
  ,NOM_TACHE            VARCHAR2(50)                        NOT NULL
  ,EXECUTABLE           VARCHAR2(256)                       NOT NULL
  ,PARAMETRE            VARCHAR2(1024)                      NOT NULL
  ,REPERTOIRE           VARCHAR2(256)                       NOT NULL
  ,REPERTOIRE_JOURNAL   VARCHAR2(256)                       NOT NULL
  ,EXECUTION            CHAR(2)         DEFAULT 'AC'        NOT NULL
  ,TYPE_NOTIF           CHAR(2)         DEFAULT 'OF'        NOT NULL
  ,TYPE_NOTIF_JOURNAL   CHAR(2)         DEFAULT 'OF'        NOT NULL
  ,DESTI_NOTIF          VARCHAR2(30)                        NOT NULL
  ,INTERVAL             VARCHAR2(500)                       NOT NULL
  ,DELAI_AVERTISSEMENT  NUMBER(4)                           NOT NULL
  ,DH_PROCHAINE_EXEC    DATE            DEFAULT SYSDATE     NOT NULL
  ,CODE_RETOUR_SUCCES   VARCHAR2(100)   DEFAULT '{RC} = 0'  NOT NULL
  ,COMMENTAIRE          VARCHAR2(4000)
)
TABLESPACE SDBM_DATA
MONITORING;


ALTER TABLE TACHE_AGT
   ADD CONSTRAINT TAC_CHK_EXECUTION
      CHECK (EXECUTION IN (/* Actif */ 'AC',/* Inactif */ 'IN'));

ALTER TABLE TACHE_AGT
   ADD CONSTRAINT TAC_CHK_TYPE_NOTIF
      CHECK (TYPE_NOTIF IN (/* Sur erreur */ 'OF', /* Toujours */ 'AL'));

ALTER TABLE TACHE_AGT
   ADD CONSTRAINT TAC_CHK_TYPE_NOTIF_JOURNAL
      CHECK (TYPE_NOTIF_JOURNAL IN (/* Sur erreur */ 'OF',/* Vrai */ 'VR',/* Faux */ 'FA'));


ALTER TABLE TACHE_AGT
   ADD CONSTRAINT TAC_PK_TACHE_AGT PRIMARY KEY (NOM_SERVEUR, NOM_TACHE)
      USING INDEX
      TABLESPACE SDBM_DATA;


ALTER TABLE TACHE_AGT
   ADD CONSTRAINT TAC_FK_DESTI_NOTIF
       FOREIGN KEY (DESTI_NOTIF) REFERENCES DESTI_NOTIF;


INSERT INTO TACHE_AGT
SELECT NOM_SERVEUR
      ,NOM_TACHE
      ,EXECUTABLE
      ,PARAMETRE
      ,REPERTOIRE
      ,REPERTOIRE_JOURNAL
      ,EXECUTION
      ,TYPE_NOTIF
      ,'OF'
      ,DESTI_NOTIF
      ,INTERVAL
      ,DELAI_AVERTISSEMENT
      ,DH_PROCHAINE_EXEC
      ,CODE_RETOUR_SUCCES
      ,COMMENTAIRE
  FROM TACHE_AGT_OLD;

COMMIT;


ALTER TABLE TACHE_DET_MSG_AGT
   ADD CONSTRAINT TDMA_FK_TACHE_AGT
       FOREIGN KEY (NOM_SERVEUR, NOM_TACHE) REFERENCES TACHE_AGT
       ON DELETE CASCADE;

ALTER TABLE HIST_TACHE_AGT
   ADD CONSTRAINT HTA_FK_TACHE_AGT
       FOREIGN KEY (NOM_SERVEUR, NOM_TACHE) REFERENCES TACHE_AGT
       ON DELETE CASCADE;

GRANT SELECT ON SDBM.TACHE_AGT                 TO SDBMON;




ALTER TABLE DESTI_NOTIF_DETAIL DROP CONSTRAINT DND_FK_DESTI_NOTIF;
ALTER TABLE DESTI_NOTIF_DETAIL DROP CONSTRAINT DND_FK_TYPE_NOTIF;

ALTER TABLE DESTI_NOTIF_DETAIL DROP CONSTRAINT DND_CHK_RETRAIT_ACCENT;

ALTER TABLE DESTI_NOTIF_DETAIL DROP CONSTRAINT DND_PK_DESTI_NOTIF;
DROP INDEX DND_PK_DESTI_NOTIF;


ALTER TABLE DESTI_NOTIF_DETAIL RENAME TO DESTI_NOTIF_DETAIL_OLD;

CREATE TABLE DESTI_NOTIF_DETAIL
(
   DESTI_NOTIF          VARCHAR2(30)                     NOT NULL
  ,TYPE_NOTIF           VARCHAR2(30)    DEFAULT 'SMTP'   NOT NULL
  ,ADRESSE              VARCHAR2(100)                    NOT NULL
  ,RETRAIT_ACCENT       CHAR(2)         DEFAULT 'FA'     NOT NULL
  ,SUPPORT_FICHIER      CHAR(2)         DEFAULT 'VR'     NOT NULL
  ,SQL_HORAIRE          VARCHAR2(500)   DEFAULT
'
SELECT 1
  FROM DUAL
 WHERE /* JOUR  */ (TRIM(TO_CHAR(SYSDATE,''DAY'',''NLS_DATE_LANGUAGE = AMERICAN'')) IN (''MONDAY'',''TUESDAY'',''WEDNESDAY'',''THURSDAY'',''FRIDAY'',''SATURDAY'',''SUNDAY''))
   AND /* HEURE */ (TO_CHAR(SYSDATE,''HH24:MI'') BETWEEN ''00:00'' AND ''23:59'')
'                                                          
                                                                   NOT NULL
  ,COMMENTAIRE          VARCHAR2(4000)
)
TABLESPACE SDBM_DATA
MONITORING;


ALTER TABLE DESTI_NOTIF_DETAIL
   ADD CONSTRAINT DND_CHK_RETRAIT_ACCENT
      CHECK (RETRAIT_ACCENT IN (/* Vrai */ 'VR',/* Faux */ 'FA'));

ALTER TABLE DESTI_NOTIF_DETAIL
   ADD CONSTRAINT DND_CHK_SUPPORT_FICHIER
      CHECK (SUPPORT_FICHIER IN (/* Vrai */ 'VR',/* Faux */ 'FA'));

ALTER TABLE DESTI_NOTIF_DETAIL
   ADD CONSTRAINT DND_PK_DESTI_NOTIF PRIMARY KEY (DESTI_NOTIF, TYPE_NOTIF, ADRESSE)
      USING INDEX
      TABLESPACE SDBM_DATA;


ALTER TABLE DESTI_NOTIF_DETAIL
   ADD CONSTRAINT DND_FK_DESTI_NOTIF
       FOREIGN KEY (DESTI_NOTIF) REFERENCES DESTI_NOTIF
       ON DELETE CASCADE;

ALTER TABLE DESTI_NOTIF_DETAIL
   ADD CONSTRAINT DND_FK_TYPE_NOTIF
       FOREIGN KEY (TYPE_NOTIF) REFERENCES PARAMETRE_NOTIF_EXT;


INSERT INTO DESTI_NOTIF_DETAIL
SELECT DESTI_NOTIF
      ,TYPE_NOTIF
      ,ADRESSE
      ,RETRAIT_ACCENT
      ,'VR'
      ,SQL_HORAIRE
      ,COMMENTAIRE
  FROM DESTI_NOTIF_DETAIL_OLD;

COMMIT;


@../_package/ps-sdbm_smtp.sql
@../_package/pb-sdbm_smtp.sql
@../_package/ps-sdbm_util.sql
@../_package/pb-sdbm_util.sql
@../_package/pb-sdbm_agent.sql
