-- *
-- * Copyright (c) 2008-2024 Benoit Bouthillier. All rights reserved.
-- * Licensed under the MIT license.
-- * See LICENSE file in the project root for full license information.
-- *


CREATE OR REPLACE PACKAGE CONV_MDP_USAGER_TEMP
IS

   FUNCTION DECRYPTER_MDP_USAGER
   (
      A_NOM_USAGER IN USAGER.NOM_USAGER%TYPE
     ,A_MDP_ENC    IN USAGER.MOT_PASSE%TYPE
   )
   RETURN VARCHAR2;
   PRAGMA RESTRICT_REFERENCES(DECRYPTER_MDP_USAGER,WNDS,WNPS,TRUST);

   FUNCTION DECRYPTER_MDP_CIBLE
   (
      A_NOM_CIBLE   IN CIBLE.NOM_CIBLE%TYPE
     ,A_MDP_ENC     IN CIBLE.MDP_USAGER%TYPE
   )
   RETURN VARCHAR2;
   PRAGMA RESTRICT_REFERENCES(DECRYPTER_MDP_CIBLE,WNDS,WNPS,TRUST);

   FUNCTION DECRYPTER_MDP_SMTP
   (
      A_NOM_USAGER  IN PARAMETRE.NOM_USAGER_SMTP%TYPE
     ,A_MDP_ENC     IN PARAMETRE.MDP_USAGER_SMTP%TYPE
   )
   RETURN VARCHAR2;
   PRAGMA RESTRICT_REFERENCES(DECRYPTER_MDP_SMTP,WNDS,WNPS,TRUST);

END CONV_MDP_USAGER_TEMP;
/

